### ISSUE TITLE
Implement proof of concept

### ISSUE THREAD

**Issue by t-karcher** [ChrisOKay/game-off-2016#2]
**Todo**
- [x] Implement background scrolling
- [x] Implement rain
- [x] Implement HUD (for inventory etc.)
- [x] Implement flickering light
- [x] Implement player and key controls
- [x] Implement obstacles (walls, chests, ...)
- [x] Implement puzzle

All implemented in branch gameplay-test.

**Comment by t-karcher** [comment]
Flickering light was easier than expected: There's a handy Light2D node with lots of customization options.

**Comment by t-karcher** [comment]
Das Licht-Rätsel ("AFFE12") lässt sich jetzt durch Klick auf die Kiste starten.

**Comment by ChrisOKay** [comment]
machst du mal einen pull request vor sonntag?

**Comment by t-karcher** [comment]
Warum? Das ist meine Test-Branche, die wollte ich nie im Master haben, und da ist jetzt schon ziemlich viel Müll drin... Mein Plan war, die guten Teile selektiv in neue Branches zu übernehmen, sobald wir wissen, wie das Spiel genau aussehen soll...

**Comment by ChrisOKay** [comment]
dass heisst, um es zu sehen, muss ich auf den branch wechseln und pullen? oder geht das von meiner seite garnicht?

**Comment by t-karcher** [comment]
Doch, das geht problemlos, hab's mit Aaron auch schon getestet. Checkout, pull, fertig.

**Comment by t-karcher** [comment]
Alles wie geplant umgesetzt.
